### ISSUE TITLE
optimizer press incompatibilities 

### ISSUE THREAD

**Issue by neroshin** [wp-premium/woocommerce-gravityforms-product-addons#1]
hello support, the plugin is not working in optimizer press 2 could you help me to solve it thank you.

**Comment by remcotolsma** [comment]
Go to https://woocommerce.com/ » Support » "Help Desk" for support, this is only a mirror of the "WooCommerce Gravity Forms Product Add-ons" plugin.

**Comment by neroshin** [comment]
ok remcotolsma thank you for respond.
