### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by JudeRosario** [wp-premium/woocommerce-gravityforms-product-addons#2]
How is this add on licensed ? Can we add a license file to the project ?

**Comment by remcotolsma** [comment]
```
License: GNU General Public License v3.0
License URI: http://www.gnu.org/licenses/gpl-3.0.html
```

https://github.com/wp-premium/woocommerce-gravityforms-product-addons/blob/2.10.10/gravityforms-product-addons.php#L16-L17
