### ISSUE TITLE
Problems retrieving usable data from an Address field

### ISSUE THREAD

**Issue by studio4** [wp-premium/woocommerce-gravityforms-product-addons#3]
When using the built-in Gravity Forms Address Field the form field is added as a meta_key and meta_value to wp_woocommerce_order_itemmeta but the address field array parts are stitched together with no spaces so an address like:

123 Walt Disney Walk
Disneyland
Paris 
P1 234
France

is saved as:

"123 Walt Disney WalkDisneylandParisP1 234FranceMap It"

Which is not much use, you can't even split it out because there is no spacing/character to split it out with.

**Comment by studio4** [comment]
The problem looks to be this line (https://github.com/wp-premium/woocommerce-gravityforms-product-addons/blob/master/inc/gravityforms-product-addons-cart.php#L206):

`$arr_var = (is_array( $value )) ? implode( '', $value ) : '-';`

It should probably be:

`$arr_var = (is_array( $value )) ? implode( ',', $value ) : '-';`

**Comment by HansVanEijsden** [comment]
@studio4 thank you!

**Comment by studio4** [comment]
Hans, this patch hasn't worked, in testing there was another line here https://github.com/wp-premium/woocommerce-gravityforms-product-addons/blob/master/inc/gravityforms-product-addons-cart.php#L329 which also imploded without a comma. I actually think perhaps it should be implode( ', ', $value ) however we're still getting the address through without spaces.

Any thoughts?

**Comment by remcotolsma** [comment]
https://github.com/wp-premium/woocommerce-gravityforms-product-addons

> WooCommerce - Gravity Forms Product Add-Ons, Git-ified. Synced manual! This repository is just a mirror of the WooCommerce - Gravity Forms Product Add-Ons plugin. **Please do not send pull requests and issues.**

You can get support from https://woocommerce.com/products/gravity-forms-add-ons/.
