### ISSUE TITLE
How do I store Labels as Values?

### ISSUE THREAD

**Issue by MikeBytion** [wp-premium/woocommerce-gravityforms-product-addons#4]
For instance, I have a product with a dropdown.  There is a label, value, and price associated.  For instance:

label: 10 Widgets
value: 10
price: $99

What I want is for when I look at the order to see '10 widgets' under widgets, but I see '10'. I tried the woocommerce_gforms_use_label_as_value filter but it didn't work. 

I would add that 2.10 appears to work this way out of the box.

**Comment by remcotolsma** [comment]
> WooCommerce - Gravity Forms Product Add-Ons, Git-ified. Synced manual! This repository is just a mirror of the WooCommerce - Gravity Forms Product Add-Ons plugin. **Please do not send pull requests and issues.**

https://github.com/wp-premium/woocommerce-gravityforms-product-addons

You can contact the Gravity Forms developers: https://www.gravityhelp.com/support/.
